#!/usr/bin/env python3

import sys

from math.add import add
from math.subtract import subtract
from math.multiply import mul
from math.div import div
from math.power import power
from math.factorial import factorial

if __name__ == "__main__":
    nums = list()
    for n in sys.argv[2:]:
        nums.append(int(n))

    op = sys.argv[1]
    value = 0
    if op == "add":
        value = add(*nums)
    elif op == "sub":
        value = subtract(nums[0], *nums[1:])
    elif op == "mul":
        value = mul(*nums)
    elif op == "div":
        value = div(nums[0], *nums[1:])
    elif op == "sq":
        value = power(nums[0], 2)
    elif op == "pow":
        value = power(nums[0], nums[1])
    elif op == "fact":
        value = factorial(nums[0])
    else:
        print("unknown operator: ", op)
        sys.exit(1)

    print(value)
